import { FoodItem, PersonalRecord, PricingTier, UserProfile, WeightLog, WorkoutSession } from "@/types/fitness";

export const SEED_FOODS: FoodItem[] = [
  // Proteins
  {
    id: "food-1",
    name: "Grilled Chicken Breast",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    category: "Protein",
  },
  {
    id: "food-2",
    name: "Wild Atlantic Salmon",
    servingUnit: "150g fillet",
    servingAmount: 150,
    calories: 280,
    protein: 34,
    carbs: 0,
    fats: 16,
    category: "Protein",
  },
  {
    id: "food-3",
    name: "Large Whole Egg",
    servingUnit: "1 large (50g)",
    servingAmount: 50,
    calories: 74,
    protein: 6.3,
    carbs: 0.4,
    fats: 5,
    category: "Protein",
  },
  {
    id: "food-4",
    name: "Egg Whites",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fats: 0.2,
    category: "Protein",
  },
  {
    id: "food-5",
    name: "Grass-Fed Lean Beef (93/7)",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 172,
    protein: 26,
    carbs: 0,
    fats: 7.2,
    category: "Protein",
  },
  {
    id: "food-6",
    name: "Whey Protein Isolate",
    servingUnit: "1 scoop (30g)",
    servingAmount: 30,
    calories: 120,
    protein: 27,
    carbs: 1.5,
    fats: 0.5,
    category: "Protein",
  },
  {
    id: "food-7",
    name: "Non-Fat Plain Greek Yogurt",
    servingUnit: "170g cup",
    servingAmount: 170,
    calories: 100,
    protein: 18,
    carbs: 6,
    fats: 0.7,
    category: "Dairy",
  },
  {
    id: "food-8",
    name: "Low-Fat Cottage Cheese",
    servingUnit: "150g",
    servingAmount: 150,
    calories: 125,
    protein: 18,
    carbs: 6,
    fats: 3,
    category: "Dairy",
  },

  // Carbohydrates & Grains
  {
    id: "food-9",
    name: "Rolled Oats",
    servingUnit: "40g dry",
    servingAmount: 40,
    calories: 150,
    protein: 5,
    carbs: 27,
    fats: 3,
    category: "Grains",
  },
  {
    id: "food-10",
    name: "Steamed Jasmine Rice",
    servingUnit: "150g cooked",
    servingAmount: 150,
    calories: 195,
    protein: 4.2,
    carbs: 43,
    fats: 0.5,
    category: "Grains",
  },
  {
    id: "food-11",
    name: "Baked Sweet Potato",
    servingUnit: "150g medium",
    servingAmount: 150,
    calories: 135,
    protein: 2.5,
    carbs: 31,
    fats: 0.2,
    category: "Vegetables",
  },
  {
    id: "food-12",
    name: "Quinoa",
    servingUnit: "150g cooked",
    servingAmount: 150,
    calories: 180,
    protein: 6.5,
    carbs: 32,
    fats: 2.9,
    category: "Grains",
  },
  {
    id: "food-13",
    name: "Fresh Blueberries",
    servingUnit: "100g cup",
    servingAmount: 100,
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fats: 0.3,
    category: "Fruits",
  },
  {
    id: "food-14",
    name: "Ripe Banana",
    servingUnit: "1 medium (118g)",
    servingAmount: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.3,
    category: "Fruits",
  },

  // Fats & Seeds
  {
    id: "food-15",
    name: "Hass Avocado",
    servingUnit: "1/2 medium (75g)",
    servingAmount: 75,
    calories: 120,
    protein: 1.5,
    carbs: 6.4,
    fats: 11,
    category: "Fruits",
  },
  {
    id: "food-16",
    name: "Natural Almond Butter",
    servingUnit: "1 tbsp (16g)",
    servingAmount: 16,
    calories: 98,
    protein: 3.4,
    carbs: 3,
    fats: 8.9,
    category: "Snacks",
  },
  {
    id: "food-17",
    name: "Extra Virgin Olive Oil",
    servingUnit: "1 tbsp (14g)",
    servingAmount: 14,
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    category: "Snacks",
  },
  {
    id: "food-18",
    name: "Raw Almonds",
    servingUnit: "28g (approx 23 nuts)",
    servingAmount: 28,
    calories: 164,
    protein: 6,
    carbs: 6.1,
    fats: 14.2,
    category: "Snacks",
  },

  // Vegetables
  {
    id: "food-19",
    name: "Steamed Broccoli Florets",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 35,
    protein: 2.8,
    carbs: 7.2,
    fats: 0.4,
    category: "Vegetables",
  },
  {
    id: "food-20",
    name: "Fresh Baby Spinach",
    servingUnit: "85g (3 cups)",
    servingAmount: 85,
    calories: 20,
    protein: 2.5,
    carbs: 3.1,
    fats: 0.3,
    category: "Vegetables",
  },
];

export const DEFAULT_PROFILE: UserProfile = {
  id: "usr-demo",
  name: "Devansh Rathore",
  age: 24,
  gender: "male",
  heightCm: 180,
  currentWeightKg: 78.0,
  targetWeightKg: 75.0,
  activityLevel: "moderate",
  goal: "lose_weight",
  dailyCalorieTarget: 2200,
  targetProteinGrams: 165,
  targetCarbsGrams: 220,
  targetFatsGrams: 60,
  streakDays: 0,
  createdAt: "2026-09-01",
};

export const INITIAL_WEIGHT_LOGS: WeightLog[] = [];

export const INITIAL_WORKOUTS: WorkoutSession[] = [];

export const INITIAL_PRS: PersonalRecord[] = [];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "tier-basic",
    name: "Basic",
    priceMonthly: 0,
    priceAnnual: 0,
    description: "Essential calorie counting and baseline progress tracking for beginners.",
    features: [
      "Daily calorie goal calculator",
      "Standard food database lookup",
      "Breakfast, Lunch, Dinner logging",
      "Body weight history tracking",
      "Community food search",
    ],
    ctaText: "Start Free",
  },
  {
    id: "tier-pro",
    name: "Pro Athlete",
    priceMonthly: 12,
    priceAnnual: 99,
    description: "Advanced macro precision, custom meals, and complete strength training logs.",
    popular: true,
    features: [
      "Everything in Basic",
      "Gram precision macro splits",
      "Barcode & custom food creator",
      "Full workout & set/rep logger",
      "PR tracking & strength curves",
      "Weekly calorie consistency trends",
      "Offline sync & export",
    ],
    ctaText: "Upgrade to Pro",
  },
  {
    id: "tier-elite",
    name: "Elite Performance",
    priceMonthly: 29,
    priceAnnual: 249,
    description: "Dedicated 1-on-1 coaching integrations, metabolic adaptation, and priority support.",
    features: [
      "Everything in Pro Athlete",
      "Adaptive TDEE dynamic auto-adjuster",
      "Advanced micronutrient breakdown",
      "Coach dashboard access",
      "Custom periodized training cycles",
      "Priority 24/7 nutrition support",
    ],
    ctaText: "Go Elite",
  },
];
