import { FoodItem, PersonalRecord, PricingTier, UserProfile, WeightLog, WorkoutSession } from "@/types/fitness";

export const SEED_FOODS: FoodItem[] = [
  // Proteins
  {
    id: "food-1",
    name: "Grilled Chicken Breast",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    category: "Protein",
  },
  {
    id: "food-2",
    name: "Wild Atlantic Salmon",
    servingUnit: "150g fillet",
    servingAmount: 150,
    calories: 280,
    protein: 34,
    carbs: 0,
    fats: 16,
    category: "Protein",
  },
  {
    id: "food-3",
    name: "Large Whole Egg",
    servingUnit: "1 large (50g)",
    servingAmount: 50,
    calories: 74,
    protein: 6.3,
    carbs: 0.4,
    fats: 5,
    category: "Protein",
  },
  {
    id: "food-4",
    name: "Egg Whites",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fats: 0.2,
    category: "Protein",
  },
  {
    id: "food-5",
    name: "Grass-Fed Lean Beef (93/7)",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 172,
    protein: 26,
    carbs: 0,
    fats: 7.2,
    category: "Protein",
  },
  {
    id: "food-6",
    name: "Whey Protein Isolate",
    servingUnit: "1 scoop (30g)",
    servingAmount: 30,
    calories: 120,
    protein: 27,
    carbs: 1.5,
    fats: 0.5,
    category: "Protein",
  },
  {
    id: "food-7",
    name: "Non-Fat Plain Greek Yogurt",
    servingUnit: "170g cup",
    servingAmount: 170,
    calories: 100,
    protein: 18,
    carbs: 6,
    fats: 0.7,
    category: "Dairy",
  },
  {
    id: "food-8",
    name: "Low-Fat Cottage Cheese",
    servingUnit: "150g",
    servingAmount: 150,
    calories: 125,
    protein: 18,
    carbs: 6,
    fats: 3,
    category: "Dairy",
  },

  // Carbohydrates & Grains
  {
    id: "food-9",
    name: "Rolled Oats",
    servingUnit: "40g dry",
    servingAmount: 40,
    calories: 150,
    protein: 5,
    carbs: 27,
    fats: 3,
    category: "Grains",
  },
  {
    id: "food-10",
    name: "Steamed Jasmine Rice",
    servingUnit: "150g cooked",
    servingAmount: 150,
    calories: 195,
    protein: 4.2,
    carbs: 43,
    fats: 0.5,
    category: "Grains",
  },
  {
    id: "food-11",
    name: "Baked Sweet Potato",
    servingUnit: "150g medium",
    servingAmount: 150,
    calories: 135,
    protein: 2.5,
    carbs: 31,
    fats: 0.2,
    category: "Vegetables",
  },
  {
    id: "food-12",
    name: "Quinoa",
    servingUnit: "150g cooked",
    servingAmount: 150,
    calories: 180,
    protein: 6.5,
    carbs: 32,
    fats: 2.9,
    category: "Grains",
  },
  {
    id: "food-13",
    name: "Fresh Blueberries",
    servingUnit: "100g cup",
    servingAmount: 100,
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fats: 0.3,
    category: "Fruits",
  },
  {
    id: "food-14",
    name: "Ripe Banana",
    servingUnit: "1 medium (118g)",
    servingAmount: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.3,
    category: "Fruits",
  },

  // Fats & Seeds
  {
    id: "food-15",
    name: "Hass Avocado",
    servingUnit: "1/2 medium (75g)",
    servingAmount: 75,
    calories: 120,
    protein: 1.5,
    carbs: 6.4,
    fats: 11,
    category: "Fruits",
  },
  {
    id: "food-16",
    name: "Natural Almond Butter",
    servingUnit: "1 tbsp (16g)",
    servingAmount: 16,
    calories: 98,
    protein: 3.4,
    carbs: 3,
    fats: 8.9,
    category: "Snacks",
  },
  {
    id: "food-17",
    name: "Extra Virgin Olive Oil",
    servingUnit: "1 tbsp (14g)",
    servingAmount: 14,
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    category: "Snacks",
  },
  {
    id: "food-18",
    name: "Raw Almonds",
    servingUnit: "28g (approx 23 nuts)",
    servingAmount: 28,
    calories: 164,
    protein: 6,
    carbs: 6.1,
    fats: 14.2,
    category: "Snacks",
  },

  // Vegetables
  {
    id: "food-19",
    name: "Steamed Broccoli Florets",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 35,
    protein: 2.8,
    carbs: 7.2,
    fats: 0.4,
    category: "Vegetables",
  },
  {
    id: "food-20",
    name: "Fresh Baby Spinach",
    servingUnit: "85g (3 cups)",
    servingAmount: 85,
    calories: 20,
    protein: 2.5,
    carbs: 3.1,
    fats: 0.3,
    category: "Vegetables",
  },
  {
    id: "food-21",
    name: "Chunk Light Tuna (in water)",
    servingUnit: "100g drained",
    servingAmount: 100,
    calories: 116,
    protein: 26,
    carbs: 0,
    fats: 1,
    category: "Protein",
  },
  {
    id: "food-22",
    name: "Lean Ground Turkey (93/7)",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 150,
    protein: 20,
    carbs: 0,
    fats: 8,
    category: "Protein",
  },
  {
    id: "food-23",
    name: "Top Sirloin Steak",
    servingUnit: "150g trimmed",
    servingAmount: 150,
    calories: 270,
    protein: 42,
    carbs: 0,
    fats: 10.5,
    category: "Protein",
  },
  {
    id: "food-24",
    name: "Steamed Shrimp",
    servingUnit: "100g cooked",
    servingAmount: 100,
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fats: 0.3,
    category: "Protein",
  },
  {
    id: "food-25",
    name: "Extra-Firm Tofu",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 83,
    protein: 10,
    carbs: 2,
    fats: 5,
    category: "Protein",
  },
  {
    id: "food-26",
    name: "Tempeh",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 192,
    protein: 20,
    carbs: 7.6,
    fats: 10.8,
    category: "Protein",
  },
  {
    id: "food-27",
    name: "Shelled Edamame",
    servingUnit: "100g steamed",
    servingAmount: 100,
    calories: 122,
    protein: 11,
    carbs: 10,
    fats: 5,
    category: "Protein",
  },
  {
    id: "food-28",
    name: "Brown Rice",
    servingUnit: "150g cooked",
    servingAmount: 150,
    calories: 168,
    protein: 3.8,
    carbs: 35,
    fats: 1.4,
    category: "Grains",
  },
  {
    id: "food-29",
    name: "100% Whole Wheat Bread",
    servingUnit: "1 slice (40g)",
    servingAmount: 40,
    calories: 90,
    protein: 4.5,
    carbs: 17,
    fats: 1,
    category: "Grains",
  },
  {
    id: "food-30",
    name: "Artisan Sourdough Bread",
    servingUnit: "1 slice (50g)",
    servingAmount: 50,
    calories: 120,
    protein: 4,
    carbs: 23,
    fats: 0.8,
    category: "Grains",
  },
  {
    id: "food-31",
    name: "Whole Wheat Pasta",
    servingUnit: "100g cooked",
    servingAmount: 100,
    calories: 140,
    protein: 6,
    carbs: 30,
    fats: 0.8,
    category: "Grains",
  },
  {
    id: "food-32",
    name: "Baked Russet Potato",
    servingUnit: "150g with skin",
    servingAmount: 150,
    calories: 145,
    protein: 3.8,
    carbs: 33,
    fats: 0.2,
    category: "Vegetables",
  },
  {
    id: "food-33",
    name: "Cream of Rice",
    servingUnit: "45g dry",
    servingAmount: 45,
    calories: 160,
    protein: 3,
    carbs: 36,
    fats: 0,
    category: "Grains",
  },
  {
    id: "food-34",
    name: "Plain Bagel",
    servingUnit: "1 bagel (95g)",
    servingAmount: 95,
    calories: 245,
    protein: 9,
    carbs: 48,
    fats: 1.5,
    category: "Grains",
  },
  {
    id: "food-35",
    name: "Whole Wheat Tortilla",
    servingUnit: "1 wrap (45g)",
    servingAmount: 45,
    calories: 130,
    protein: 4,
    carbs: 22,
    fats: 3,
    category: "Grains",
  },
  {
    id: "food-36",
    name: "Honeycrisp Apple",
    servingUnit: "1 medium (150g)",
    servingAmount: 150,
    calories: 80,
    protein: 0.4,
    carbs: 21,
    fats: 0.2,
    category: "Fruits",
  },
  {
    id: "food-37",
    name: "Fresh Strawberries",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fats: 0.3,
    category: "Fruits",
  },
  {
    id: "food-38",
    name: "Navel Orange",
    servingUnit: "1 medium (130g)",
    servingAmount: 130,
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fats: 0.2,
    category: "Fruits",
  },
  {
    id: "food-39",
    name: "Pineapple Chunks",
    servingUnit: "100g fresh",
    servingAmount: 100,
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fats: 0.1,
    category: "Fruits",
  },
  {
    id: "food-40",
    name: "Fresh Watermelon",
    servingUnit: "150g diced",
    servingAmount: 150,
    calories: 45,
    protein: 0.9,
    carbs: 11.5,
    fats: 0.2,
    category: "Fruits",
  },
  {
    id: "food-41",
    name: "Fresh Raspberries",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 52,
    protein: 1.2,
    carbs: 11.9,
    fats: 0.7,
    category: "Fruits",
  },
  {
    id: "food-42",
    name: "Grilled Asparagus Spears",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 22,
    protein: 2.4,
    carbs: 4.1,
    fats: 0.2,
    category: "Vegetables",
  },
  {
    id: "food-43",
    name: "Fresh Zucchini Slices",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 17,
    protein: 1.2,
    carbs: 3.1,
    fats: 0.3,
    category: "Vegetables",
  },
  {
    id: "food-44",
    name: "Bell Peppers (Mixed)",
    servingUnit: "100g chopped",
    servingAmount: 100,
    calories: 26,
    protein: 1,
    carbs: 6,
    fats: 0.3,
    category: "Vegetables",
  },
  {
    id: "food-45",
    name: "Steamed Cauliflower",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fats: 0.3,
    category: "Vegetables",
  },
  {
    id: "food-46",
    name: "Baby Carrots",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fats: 0.2,
    category: "Vegetables",
  },
  {
    id: "food-47",
    name: "Green Beans",
    servingUnit: "100g steamed",
    servingAmount: 100,
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fats: 0.1,
    category: "Vegetables",
  },
  {
    id: "food-48",
    name: "Crisp Cucumber Slices",
    servingUnit: "100g",
    servingAmount: 100,
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fats: 0.1,
    category: "Vegetables",
  },
  {
    id: "food-49",
    name: "Natural Creamy Peanut Butter",
    servingUnit: "2 tbsp (32g)",
    servingAmount: 32,
    calories: 190,
    protein: 8,
    carbs: 7,
    fats: 16,
    category: "Snacks",
  },
  {
    id: "food-50",
    name: "Raw English Walnuts",
    servingUnit: "28g (approx 14 halves)",
    servingAmount: 28,
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fats: 18.5,
    category: "Snacks",
  },
  {
    id: "food-51",
    name: "Black Chia Seeds",
    servingUnit: "1 tbsp (12g)",
    servingAmount: 12,
    calories: 58,
    protein: 2,
    carbs: 5,
    fats: 3.7,
    category: "Snacks",
  },
  {
    id: "food-52",
    name: "Unsweetened Almond Milk",
    servingUnit: "1 cup (240ml)",
    servingAmount: 240,
    calories: 30,
    protein: 1,
    carbs: 1,
    fats: 2.5,
    category: "Dairy",
  },
  {
    id: "food-53",
    name: "Ultra-Filtered Skim Milk (Fairlife)",
    servingUnit: "1 cup (240ml)",
    servingAmount: 240,
    calories: 80,
    protein: 13,
    carbs: 6,
    fats: 0,
    category: "Dairy",
  },
  {
    id: "food-54",
    name: "Whole Milk",
    servingUnit: "1 cup (240ml)",
    servingAmount: 240,
    calories: 149,
    protein: 8,
    carbs: 12,
    fats: 8,
    category: "Dairy",
  },
  {
    id: "food-55",
    name: "Part-Skim Mozzarella Shreds",
    servingUnit: "28g (1/4 cup)",
    servingAmount: 28,
    calories: 85,
    protein: 7,
    carbs: 1,
    fats: 6,
    category: "Dairy",
  },
  {
    id: "food-56",
    name: "Sharp Cheddar Cheese",
    servingUnit: "28g (1 slice)",
    servingAmount: 28,
    calories: 115,
    protein: 7,
    carbs: 0.5,
    fats: 9.5,
    category: "Dairy",
  },
  {
    id: "food-57",
    name: "Quest Nutrition Protein Bar",
    servingUnit: "1 bar (60g)",
    servingAmount: 60,
    calories: 200,
    protein: 21,
    carbs: 22,
    fats: 7,
    category: "Snacks",
  },
  {
    id: "food-58",
    name: "Plain Crispy Rice Cakes",
    servingUnit: "2 cakes (18g)",
    servingAmount: 18,
    calories: 70,
    protein: 1.5,
    carbs: 15,
    fats: 0.5,
    category: "Snacks",
  },
  {
    id: "food-59",
    name: "Dark Chocolate (85% Cacao)",
    servingUnit: "30g (3 squares)",
    servingAmount: 30,
    calories: 175,
    protein: 2.8,
    carbs: 11,
    fats: 14,
    category: "Snacks",
  },
  {
    id: "food-60",
    name: "Air-Popped Popcorn",
    servingUnit: "30g (approx 3.5 cups)",
    servingAmount: 30,
    calories: 115,
    protein: 3.5,
    carbs: 22,
    fats: 1.3,
    category: "Snacks",
  },
];

export const DEFAULT_PROFILE: UserProfile = {
  id: "usr-demo",
  name: "Devansh Rathore",
  age: 24,
  gender: "male",
  heightCm: 180,
  currentWeightKg: 78.0,
  targetWeightKg: 75.0,
  activityLevel: "moderate",
  goal: "lose_weight",
  dailyCalorieTarget: 2200,
  targetProteinGrams: 165,
  targetCarbsGrams: 220,
  targetFatsGrams: 60,
  streakDays: 0,
  createdAt: "2026-09-01",
};

export const INITIAL_WEIGHT_LOGS: WeightLog[] = [];

export const INITIAL_WORKOUTS: WorkoutSession[] = [];

export const INITIAL_PRS: PersonalRecord[] = [];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: "tier-basic",
    name: "Basic",
    priceMonthly: 0,
    priceAnnual: 0,
    description: "Essential calorie counting and baseline progress tracking for beginners.",
    features: [
      "Daily calorie goal calculator",
      "Standard food database lookup",
      "Breakfast, Lunch, Dinner logging",
      "Body weight history tracking",
      "Community food search",
    ],
    ctaText: "Start Free",
  },
  {
    id: "tier-pro",
    name: "Pro Athlete",
    priceMonthly: 12,
    priceAnnual: 99,
    description: "Advanced macro precision, custom meals, and complete strength training logs.",
    popular: true,
    features: [
      "Everything in Basic",
      "Gram precision macro splits",
      "Barcode & custom food creator",
      "Full workout & set/rep logger",
      "PR tracking & strength curves",
      "Weekly calorie consistency trends",
      "Offline sync & export",
    ],
    ctaText: "Upgrade to Pro",
  },
  {
    id: "tier-elite",
    name: "Elite Performance",
    priceMonthly: 29,
    priceAnnual: 249,
    description: "Dedicated 1-on-1 coaching integrations, metabolic adaptation, and priority support.",
    features: [
      "Everything in Pro Athlete",
      "Adaptive TDEE dynamic auto-adjuster",
      "Advanced micronutrient breakdown",
      "Coach dashboard access",
      "Custom periodized training cycles",
      "Priority 24/7 nutrition support",
    ],
    ctaText: "Go Elite",
  },
];
